"""Update: Payroll model

Revision ID: 0a46b7961332
Revises: 172f1e0035ee
Create Date: 2025-05-10 12:16:44.786486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a46b7961332'
down_revision: Union[str, None] = '172f1e0035ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('housing_allowance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('transport_allowance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('health_allowance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('total_allowances', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'total_allowances')
    op.drop_column('payrolls', 'health_allowance')
    op.drop_column('payrolls', 'transport_allowance')
    op.drop_column('payrolls', 'housing_allowance')
    # ### end Alembic commands ###
