"""update: User

Revision ID: 111a3176b677
Revises: 97ac498e6211
Create Date: 2025-05-10 16:26:19.018827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111a3176b677'
down_revision: Union[str, None] = '97ac498e6211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('team_lead_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], name='fk_departments_team_lead_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'user_departments', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_users_department_id', 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_department_id', 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_departments', type_='foreignkey')
    op.drop_table('departments')
    # ### end Alembic commands ###
