"""New: Payroll model

Revision ID: 172f1e0035ee
Revises: 2848f13f20ad
Create Date: 2025-05-10 11:08:39.959045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172f1e0035ee'
down_revision: Union[str, None] = '2848f13f20ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payrolls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('basic_pay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_employment_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('employment_type_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('employment_type_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('payroll_class_id', sa.Uuid(), nullable=True))
    op.drop_constraint('users_supervisor_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'payrolls', ['payroll_class_id'], ['id'])
    op.create_foreign_key(None, 'users', 'employment_types', ['employment_type_id'], ['id'])
    op.drop_column('users', 'supervisor_id')
    op.drop_column('users', 'basic_pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('basic_pay', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_supervisor_id_fkey', 'users', 'users', ['supervisor_id'], ['id'])
    op.drop_column('users', 'payroll_class_id')
    op.drop_column('users', 'employment_type_id')
    op.drop_table('user_employment_types')
    op.drop_table('payrolls')
    op.drop_table('employment_types')
    # ### end Alembic commands ###
