"""Update: User, supervisor, bank, employment type

Revision ID: 2848f13f20ad
Revises: cf7cf4d9db61
Create Date: 2025-05-10 00:23:50.965957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2848f13f20ad'
down_revision: Union[str, None] = 'cf7cf4d9db61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('employment_type_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('supervisor_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'supervisor_id')
    op.drop_table('employment_types')
    # ### end Alembic commands ###
