"""Update: User model

Revision ID: 29caa8125dcd
Revises: fc368990ca7f
Create Date: 2025-05-21 15:55:38.545834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29caa8125dcd'
down_revision: Union[str, None] = 'fc368990ca7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('role_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_column('role_permissions', 'role_id')
    # ### end Alembic commands ###
