"""Update: Payroll model

Revision ID: 536f8fdca88e
Revises: 86afa957096e
Create Date: 2025-05-10 14:14:02.136944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536f8fdca88e'
down_revision: Union[str, None] = '86afa957096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employment_types', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employment_types', type_='unique')
    # ### end Alembic commands ###
