"""update: User

Revision ID: 6c2b646c00d2
Revises: bc27e8ce1cf5
Create Date: 2025-05-10 16:13:56.072023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2b646c00d2'
down_revision: Union[str, None] = 'bc27e8ce1cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('team_lead_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['team_lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'team_lead_id')
    # ### end Alembic commands ###
