"""Update: User model - rename role to roles

Revision ID: 7c8550ea87fa
Revises: 2006b9d512db
Create Date: 2025-05-03 13:16:17.133368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8550ea87fa'
down_revision: Union[str, None] = '2006b9d512db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_supervisors_role', table_name='user_supervisors')
    op.drop_column('user_supervisors', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_supervisors', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_user_supervisors_role', 'user_supervisors', ['role'], unique=True)
    # ### end Alembic commands ###
