"""Update: User model - rename role to roles

Revision ID: 9599addee5c5
Revises: 7c8550ea87fa
Create Date: 2025-05-03 13:29:25.796685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9599addee5c5'
down_revision: Union[str, None] = '7c8550ea87fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_supervisors', sa.Column('role', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_user_supervisors_role'), 'user_supervisors', ['role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supervisors_role'), table_name='user_supervisors')
    op.drop_column('user_supervisors', 'role')
    # ### end Alembic commands ###
