"""Update: Attendance Model

Revision ID: b1385f8970ec
Revises:
Create Date: 2025-05-02 15:07:01.661111

"""

from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM


from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b1385f8970ec"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('attendance', sa.Column('total_hours', sa.Integer(), nullable=True))
#     op.add_column('attendance', sa.Column('clock_in_status', sa.Enum('EARLY', 'LATE', 'PRESENT', name='attendance_clock_type_enum'), nullable=False))
#     op.add_column('attendance', sa.Column('clock_out_status', sa.Enum('EARLY', 'LATE', 'PRESENT', name='attendance_clock_type_enum'), nullable=True))
#     # ### end Alembic commands ###


def upgrade() -> None:
    attendance_clock_enum = ENUM('EARLY', 'LATE', 'PRESENT', name='attendance_clock_type_enum', create_type=True)

    # Create the Enum type
    op.execute("CREATE TYPE attendance_clock_type_enum AS ENUM('EARLY', 'LATE', 'PRESENT')")

    # Add the column as nullable first
    op.add_column('attendance', sa.Column('clock_in_status', attendance_clock_enum, nullable=True))
    
    # Add other columns
    op.add_column('attendance', sa.Column('clock_out_status', attendance_clock_enum, nullable=True))
    op.add_column('attendance', sa.Column('total_hours', sa.Integer(), nullable=True))

    # Update existing rows to set a default value (e.g., 'PRESENT')
    op.execute("UPDATE attendance SET clock_in_status = 'PRESENT' WHERE clock_in_status IS NULL")

    # Alter the column to be NOT NULL after the update
    op.alter_column('attendance', 'clock_in_status', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attendance", "clock_out_status")
    op.drop_column("attendance", "clock_in_status")
    op.drop_column("attendance", "total_hours")
    # ### end Alembic commands ###
