"""update: Attendance

Revision ID: d22b0881f055
Revises: 99ac16c407f9
Create Date: 2025-05-02 23:38:26.147681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22b0881f055'
down_revision: Union[str, None] = '99ac16c407f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('attendance_team_lead_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('attendance', 'team_lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('team_lead_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_team_lead_id_fkey', 'attendance', 'users', ['team_lead_id'], ['id'], ondelete='SET NULL')
    op.drop_column('attendance', 'user_id')
    # ### end Alembic commands ###
